#ifndef TESTCPPDEMO_GLOBAL_H
#define TESTCPPDEMO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TESTCPPDEMO_LIBRARY)
#  define TESTCPPDEMOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TESTCPPDEMOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TESTCPPDEMO_GLOBAL_H
