#ifndef DEVLANGCHOOSE_GLOBAL_H
#define DEVLANGCHOOSE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DEVLANGCHOOSE_LIBRARY)
#  define DEVLANGCHOOSESHARED_EXPORT Q_DECL_EXPORT
#else
#  define DEVLANGCHOOSESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DEVLANGCHOOSE_GLOBAL_H
