#ifndef TA_MUTILMSGBOX_GLOBAL_H
#define TA_MUTILMSGBOX_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TA_MUTILMSGBOX_LIBRARY)
#  define TA_MUTILMSGBOXSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TA_MUTILMSGBOXSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TA_MSGBOX_GLOBAL_H
