#ifndef LOCALSQLITE_GLOBAL_H
#define LOCALSQLITE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LOCALSQLITE_LIBRARY)
#  define LOCALSQLITESHARED_EXPORT Q_DECL_EXPORT
#else
#  define LOCALSQLITESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LOCALSQLITE_GLOBAL_H
